repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: "v3.10.0-2"
    hooks:
      - id: shfmt # native (requires/installs Go to build)
      # - id: shfmt-docker # Docker image (requires Docker to run)

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        entry: prettier --write --ignore-unknown
        types_or: [json, yaml, markdown]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.8.4"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.6
    hooks:
      - id: uv-export
        name: uv-export requirements-base.txt
        args: [--no-dev, -o, requirements/base.txt]
      - id: uv-export
        name: uv-export requirements-dev.txt
        args: [--dev, -o, requirements/dev.txt]
