x-common: &common
  env_file:
    - .env.dev

services:
  app:
    <<: [*common]
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true
