x-common: &common
  env_file:
    - .env.dev
  restart: unless-stopped

services:
  fastapi-ptb:
    <<: [*common]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
